version: '3'

services:
  calculadora:
    image: calculadora:dev
    environment:
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_calculadora$
    volumes:
      - C:\Users\moises.correa\Desktop\newSolution\Calculadora:C:\app
      - C:\Users\moises.correa\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_calculadora$
    entrypoint: cmd /c "set DISABLE_PERFORMANCE_DEBUGGER=1 & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_calculadora$ bin\\Debug\\netcoreapp2.0\\Calculadora.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"